factorize retrieving document information for contents of text viewer
eclipselabs/eclipse-language-service pull request #21
Opened 2016-09-12 19:42 UTC by vladdu

Several operations need to detect information on the file in a text viewer. The required magical incantations are extracted to a helper method. If it looks ok, I can let the operations use this method.

I'm not sure if LSPDocumentInfo should be a standalone class?

BTW, I suppose even the completion processor should use this (instead of going for the currently active editor)?

2016-09-13 06:26 UTC, mickaelistria commented
That seems to be an interesting idea. However, please include in your commit some changes that actually take advantage of the refactoring. It's difficult to evaluate the relevancy or value of such change without an example of usage.

2016-09-13 14:34 UTC, vladdu commented
It's not an original idea, you had a "TODO: factorize" comment in there :wink: 

I used this in three places. Something similar might be useful to do with editors.

2016-09-13 14:39 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/completion/LSContentAssistProcessor.java
> +        final LSPDocumentInfo info = LSPEclipseUtils.getLSPDocumentInfoFor(viewer);
It seems to me that this remove the ability to have several language servers for a single file and to pick the right one (using the Predicate of `LanguageServerAccessor.getLanguageServer(file, viewer, predicate)`). This feature is important so the predicate should be an argument of `LSPEclipseUtils.getLSPDocumentInFor`

2016-09-13 14:46 UTC, vladdu commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/completion/LSContentAssistProcessor.java
> +        final LSPDocumentInfo info = LSPEclipseUtils.getLSPDocumentInfoFor(viewer);
You're right, I forgot about that, will refactor.

2016-09-14 13:46 UTC, vladdu commented
Ok, I fixed the compilation errors and added ServerCapabilities parameter.

2016-09-14 13:49 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +	public static class LSPDocumentInfo {
I would rather see this method in the LanguageServiceAccessor and the LanguageServiceAccessor.getLanguageServer() made private then. WDYT?

2016-09-14 14:09 UTC, vladdu commented
Moved new method to LanguageServiceAccessor. I'm not sure about making getLanguageServer private, because there may be use cases where one has an IFile without a text viewer. Maybe you can make a more educated guess?

2016-09-14 14:12 UTC, mickaelistria commented
> I'm not sure about making getLanguageServer private, because there may be use cases where one has an IFile without a text viewer.

At the moment, I don't think we have a use-case for that, do we? If not, then I believe it's better to make it private until we find a good reason for it to become public. Reducing visibility at maximum usually makes maintenance cheaper and easier.

2016-09-14 14:13 UTC, vladdu commented
Ok, would even the deprecated variant of the metod be made private? I assume it wasn't already done because some client uses it?

2016-09-14 14:24 UTC, mickaelistria commented
I believe the Deprecated may be a leftover of before the addition of the predicate. If you find no usage of this method in the project, feel free to remove it by the way.

2016-09-14 14:26 UTC, vladdu commented
Hmm, when the file is open in an editor, I don't know how to access the source viewer, because the getter is protected. Is there a way to retrieve it, or should there be a getLSPDocumentInfoFor(AbstractTextEditor, ServerCapabilities) too?

2016-09-14 15:05 UTC, vladdu commented
I think we should use consistently jus tone of ITextFileBufferManager.DEFAULT or FileBuffers.getTextFileBufferManager() - which one is better?

2016-09-14 15:06 UTC, mickaelistria commented
> I think we should use consistently jus tone of ITextFileBufferManager.DEFAULT or FileBuffers.getTextFileBufferManager() - which one is better? 

Sure, but I don't know which one is better ;) Maybe you can ask it to the platform-dev mailing-list?

2016-09-14 18:03 UTC, vladdu commented
After checking the code, FileBuffers.getTextFileBufferManager() is safer (returns null instead of throwing NPE, if there is an error).

It looks like LanguageServiceAccessor.getLanguageServer is still needed: marker resolution is done outlside of an editor/viewer context, we only know the resource.

BTW, is it ok to simplify the code with lambda expressions?

2016-09-14 18:21 UTC, vladdu commented
I have added a method with an editor parameter; I believe I got all the parameter values right.

I found a place where LanguageServiceAccessor.getLanguageServer(IFile, IDocument) is used: in the marker resolution code. Should we keep this method or force users to pass null as the third argument?

2016-09-15 07:01 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/codelens/LSPCodeLensMenu.java
> +			info = LanguageServiceAccessor.getLSPDocumentInfoFor((ITextEditor) editor, null);
the predicate should be `capabilities -> { capabilites.getCodelensProvider() != null }` rather than `null`.

2016-09-15 07:02 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/completion/LSContentAssistProcessor.java
> +        final LSPDocumentInfo info = LanguageServiceAccessor.getLSPDocumentInfoFor(viewer, ServerCapabilities::isCodeActionProvider);
Indentation seems inconsistent here. Please indent with tabs, then align (inside the line) with spaces).

2016-09-15 07:02 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/completion/LSContentAssistProcessor.java
> +            if (info.languageClient != null) {
same thing about indentation.

2016-09-15 07:09 UTC, mickaelistria requested changes
The overall change looks good, as it saves a lot of repeated lines.
I tried it, and it's working without issue for OmniSharp.

The only change I'd like to request before we can merge is the indentation on one of the block (which is using spaces rather than tabs). Mixing indentation makes reviewing code on different editors/viewers (GitHub, Eclipse, vim, Gerrit...) tricky, so I believe it's worth it.
Other comments are more "nice-to-have" that can be considered in another patchset.

2016-09-15 07:09 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +					if (request == null || wrapper.getServerCapabilities() == null
I don't like much this alignment, but let's just not make it a blocker.

2016-09-15 07:18 UTC, vladdu commented
Will fix. 

I used the default Eclipse settings for formatting and indentation, and tried to not mess the existing code too much, but it's a bit tedious. What settings should I use? Can we commit these with the project?

2016-09-15 07:40 UTC, mickaelistria commented
Settings I use (in the workspace so I don't have .settings to commit)
* No limit to line width
* Tabs to indent
Settings I should use but don't
* Remove trailing whitespaces on modified lines

Yes, we can and should commit some project settings to avoid the reviewer to be too annoying with the nice contributors ;) If you want to contribute some, please make another PR for that. Divide and rule!

2016-09-15 14:18 UTC, vladdu commented
I think I will wait for a resolution on the formatter PR, then I wil rebase.

2016-09-15 20:51 UTC, vladdu commented
I have restored the formatting, hopefully without missing some spots. 

[I have to say that this is the worst part: fixing something in 10 minutes and then spending an hour to clean up spurious formatting changes... I wish there was a way to commit with standard formatting rules, but reformat everything with my own settings on checkout - now I could see something that I like, but the repository is in a stable format. This won't handle manual formatting, though...]

2016-09-16 05:58 UTC, mickaelistria commented
Rebased and merged as f8975dd6f4e8b7210a874174d331daa0ee5d7978, thanks.
About formatting and other things, the most efficient approach is always to not change anything to unrelated lines, and to adopt the convention that's already used in the file. So the review only focus on code.
Formatting is better discussed in separate issues, like you did in #22 . It makes it easier to have progress in both topics simultaneously when mixing it in a single issue usually slows down the review and "time to market".

2016-09-16 06:18 UTC, closed without merging