add format and cleanup settings; reformat code accordingly
eclipselabs/eclipse-language-service pull request #22
Opened 2016-09-15 14:17 UTC by vladdu

The settings are the default "Eclipse" built-in profiles, with the
following changes:

Format:
- use spaces to indent wrapped lines
- add missing new line at EOF
- reformat even comments
- allow on/off tags to suppress formatting

Clean up:
- organize imports
- remove trailing whitespace
- remove redundant type arguments

TL;DR: The default formatter has a page width of 120 chars, and 80
chars for comments. Indentation is with tabs.

2016-09-15 14:21 UTC, vladdu commented
Some of the ways the code is reformatted might not be to your liking :-) but IMHO it is better to have a consistent format.

2016-09-15 14:30 UTC, mickaelistria commented
The only one I'd argue here is "reformat even comments". Pretty often, for long lines for example, it's necassary to put it on several lines; when this happens, developers caring about readability use some purely human decision to know how to split: 1 line per argument, or 1 line per series of similar arguments, or for boolean to emphasize what the decision tree is, or if you think about a matrix, using rows and columns... For comments, it's the same. Breaklines, new lines or indentation can be important to emphasize ideas.
I don't think an automated formatter should in any case decide in place of a developer. Default rules are nice as suggestion when writing code, but if one decides it's better other way, it's to be respected by the formatter.

2016-09-15 14:40 UTC, vladdu commented
Ok, will remove those settings. 

There is a "Format Javadoc comments" that is enabled by default and does a pretty good job at doing the right thing for Javadoc (see the example in the formatter preview). Should that be enabled?

2016-09-15 14:43 UTC, mickaelistria commented
Yeah, I think it's fine for Javadoc since it allows HTML.

2016-09-15 14:46 UTC, vladdu commented
changed and reformatted everything

2016-09-15 14:49 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +	        IDocument document) throws BadLocationException {
Do you like this kind of things? I'm not convinced about the benefit of limiting line width if it ends with many lines splitted.

2016-09-15 14:49 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +			if (uri.startsWith(aProject.getLocationURI().toString()) && (project == null
here it would be easier to read if the line break were before of after `&&` so we see the 2 operands.

2016-09-15 14:51 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPStreamConnectionProviderRegistry.java
> +					ILaunchConfiguration config = LaunchConfigurationStreamProvider.findLaunchConfiguration(launchType,
here too, I don't see how splitting the line makes it any better for maintainers.

2016-09-15 14:52 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPStreamConnectionProviderRegistry.java
> +		return Arrays.asList(connections.stream().filter(entry -> {
the formatting here is much more complicated to read than earlier. It's a regular issue with automatic formatting when doing some "fluent APIs",

2016-09-15 14:52 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +	        Predicate<ServerCapabilities> request) throws IOException {
Is this really what we want?

2016-09-15 14:53 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +	        throws IOException {
Is this really what we want?

2016-09-15 14:53 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +			if (wrapper != null && (request == null || wrapper
same here, formatting makes it more difficult to figure the operation tree.

2016-09-15 14:53 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +				        .findProviderFor(contentType)) {
Is this really what we want?

2016-09-15 14:54 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +					if (request == null || wrapper
uglier, isn't it ;)

2016-09-15 14:54 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/languages/InitializeLaunchConfigurations.java
> +		        .getLaunchConfigurationType(IExternalToolConstants.ID_PROGRAM_LAUNCH_CONFIGURATION_TYPE);
Is this really better?

2016-09-15 14:55 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/languages/InitializeLaunchConfigurations.java
> +				        "/home/mistria/git/omnisharp-node-client/languageserver/server.js");
Is this really better?

2016-09-15 14:56 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/languages/csharp/CSharpKeywordsHighlighter.java
> +	private Set<String> keywords = new HashSet<>(Arrays.asList(new String[] { "abstract", "as", "base", "bool", "break",
This is exactly where an automatic formatter shows it doesn't really know how to communicate with humans ;)

2016-09-15 14:59 UTC, mickaelistria requested changes
I've highlighted some cases where formatter makes code less readable and maintainable IMO.
However, I think the rules set up are good recommendations, but that some parts of the existing code already are better formatted than the formatter can do. So I would suggest to apply the .settings/ but leave the current code unchanged, and we'll adopt the formatting rules progressively as we update code.

2016-09-15 15:11 UTC, vladdu commented
Some of the ugly changes can be skipped by using @formatter:off and @formatter:on comments around the region in question. But it doesn't work for all cases.

I agree that some long lines with many operations will get split in weird places, but I would argue that this means that those operations should probably be extracted into functions, usually making the meaning of those operations more clear too. If you are open for this kind of changes, I can submit some for review, to make clear what I mean.

2016-09-15 15:17 UTC, mickaelistria commented
Let's keep item separated:
* Adding formatting rules as "recommendations" for new code: OK
* Making formatter applied automatically on existing code: Not, human often format for good reasons that formatter doesn't get
* Formatting all the existing code according to the rules: Not, as it reduces readability in multiple places
* Improving code by introducing meaningful variables or functions: Yes

2016-09-15 18:49 UTC, vladdu commented
All right, I will do so. Hopefully, after improving the code there will be few (if any) places affected negatively by the formatting.

2016-09-15 19:05 UTC, vladdu commented
Kept only the formatting options, to be used as the recommended settings.

2016-09-16 05:45 UTC, merged

2016-09-16 05:45 UTC, mickaelistria commented
Merged, thanks!