factorize some common usage patterns
eclipselabs/eclipse-language-service pull request #23
Opened 2016-09-16 08:26 UTC by vladdu

This shortens some of the lines of code and lowers code duplication.

2016-09-16 08:38 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +	public static void replaceRangeInDocument(IDocument document, TextEdit textEdit) throws BadLocationException {
I'd rather see it called `applyTextEdit`

2016-09-16 08:39 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		private final LanguageClientEndpoint languageClient;
mixing public field and getters/setters is not recommended if we want the API to be uniform. Either keep it public and remove getters/setters or wrap them all in getters/setters.

2016-09-16 08:40 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		public boolean hasLanguageClient() {
I'm not convinced about the need for such method compared to a null check. I find null check are explicit and simple enough to not bother introducing some APIs doing it.

2016-09-16 08:41 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +			return hasLanguageClient();
StackOverflowException ;) I guess you wanted to write `this.languageClient != null`

2016-09-16 08:42 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/operations/completion/LSContentAssistProcessor.java
> +			if (info.hasLanguageClient()) {
Should an info without a language client even be allowed? If we add the good assertions and Nullable annotation to LSPDocumentInfo, then we shouldn't have to check for that.

2016-09-16 08:43 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
>  		}
Related here: fileUri, document and language client should be check for non-nullability. Feel free to add a dependency to JDT's Nullable annotation if it helps.

2016-09-16 08:44 UTC, mickaelistria requested changes

2016-09-19 15:08 UTC, vladdu commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
>  		}
As the code looke like now, if the editor input is not an IFileEditorInput or an IURIEditorInput, then the document may be null. Can that happen in practice?

2016-09-19 15:11 UTC, vladdu commented
I think I adressed all the comments (except of info.document's nullability).

2016-09-19 15:19 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +	public static void replaceRangeInDocument(IDocument document, TextEdit textEdit) throws BadLocationException {
Seems like this comment wasn't addressed (or I'm looking at the wrong commit)

2016-09-19 15:21 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		private LSPDocumentInfo(@NonNull URI fileUri, IFile file, IDocument document, @NonNull LanguageClientEndpoint languageClient) {
Why not keeping this constructor public and avoid the factory method? Note that I'm not against it, I'm just unsure why this is any better.

2016-09-19 15:23 UTC, vladdu commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LSPEclipseUtils.java
> +	public static void replaceRangeInDocument(IDocument document, TextEdit textEdit) throws BadLocationException {
Ah, yes, my bad, I missed that change in the commit I pushed. Fixed now.

2016-09-19 15:25 UTC, vladdu commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		private LSPDocumentInfo(@NonNull URI fileUri, IFile file, IDocument document, @NonNull LanguageClientEndpoint languageClient) {
A factory method may return null. What should we do with a constructor if fileUri or languageClient are null? The null checks would have to be duplicated (in the future there may be more methods that return a document info).

2016-09-19 15:34 UTC, mickaelistria commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		private LSPDocumentInfo(@NonNull URI fileUri, IFile file, IDocument document, @NonNull LanguageClientEndpoint languageClient) {
If we have the annotations, then users should immediately see an error in case of potential nullability of an argument. In the constructor, if there is a NonNull annotation for a null argument, then I think it would be fine to return an InvalidArgumentError.
About the null check duplication, it can be actually better: each of the consumer of the language server have to handle the case of a null fileUri by themselves, and it's better to have them checking for the nullability of the arguments and react accordingly than checking for a result that may not be usable. With the factory, doing a null check on the info is not mandatory for the client, so it can lead to NPE. With the annotations on the constructor, we know that we always get right parameters and that we can avoid the null check of info.

2016-09-19 19:01 UTC, vladdu commented on org.eclipse.languageserver/src/org/eclipse/languageserver/LanguageServiceAccessor.java
> +		private LSPDocumentInfo(@NonNull URI fileUri, IFile file, IDocument document, @NonNull LanguageClientEndpoint languageClient) {
I see. Then I should review the logic in the two LanguageServiceAccessor.getLSPDocumentInfoFor methods, who are at this moment the only places where a LSPDocumentInfo is constructed. 

Maybe you can help with some suggestions. The code is what was already written, and doesn't cover all paths: there still are some TODOs in there, making it difficult to please the compiler. What do you think getLSPDocumentInfoFor should do when fileUri or languageClient are null? Return null or throw exception?

2016-11-13 09:35 UTC, mickaelistria commented
I believe this is now outdated.

2016-11-13 09:35 UTC, closed without merging